### ISSUE TITLE
Function.prototype.apply was called on undefined

### ISSUE THREAD

**Issue by KushalDesai1** [appcircleio/appcenter-migration-tool#1]
I installed the migration tool successfully in local directory.

But when I run the command ```npx appcenter-migration-tool```, I am receiving this error.

TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at $o (/node_modules/esm/esm.js:1:224377)
    at wu (/node_modules/esm/esm.js:1:227324)
    at Eu (/node_modules/esm/esm.js:1:227999)
    at Module.<anonymous> (/node_modules/esm/esm.js:1:295976)
    at n (/node_modules/esm/esm.js:1:279589)
    at Object.<anonymous> (/node_modules/@appcircle/appcenter-migration-tool/bin/appcenter-migration-tool:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)

**Comment by BrkYld** [comment]
Hello @KushalDesai1 ,

Thank you for reaching out to us.

Could you please provide me with a bit more information?

1. Which operating system are you using?
2. What is the version of Node.js you are using?

Looking forward to your response.

**Comment by KushalDesai1** [comment]
OS: Mac OS Sequoia 15.1.1

Node Version: v22.9.0

Npm Version: 11.0.0 (Updated before installing appcenter migration tool)

> Hello @KushalDesai1 ,
> 
> Thank you for reaching out to us.
> 
> Could you please provide me with a bit more information?
> 
> 1. Which operating system are you using?
> 2. What is the version of Node.js you are using?
> 
> Looking forward to your response.

**Comment by BrkYld** [comment]
> OS: Mac OS Sequoia 15.1.1
> 
> Node Version: v22.9.0
> 
> Npm Version: 11.0.0 (Updated before installing appcenter migration tool)
> 
> > Hello @KushalDesai1 ,
> > Thank you for reaching out to us.
> > Could you please provide me with a bit more information?
> > 
> > 1. Which operating system are you using?
> > 2. What is the version of Node.js you are using?
> > 
> > Looking forward to your response.

It appears that the issue is caused by an incompatibility between the Node.js version you're using and the Appcenter Migration Tool.

You can temporarily resolve the issue by using Node.js version 21.7.3 or earlier. We will begin working on supporting newer Node.js versions as soon as possible.

Thank you for your patience!

**Comment by KushalDesai1** [comment]
I was able to run the cli after downgrading the Node.js version to 21.7.3.

Thanks @BrkYld
